// openapi.json -> schema.ts: one exported TS type per components.schemas entry (TASK-2.1,
// ADR-024). Zero dependencies on purpose (Node >= 22 only) - the subset of JSON Schema that
// pydantic/FastAPI emit is small. Deterministic, so `--check` can gate CI.
//
//   node packages/api-contract/generate.mjs          # rewrite schema.ts
//   node packages/api-contract/generate.mjs --check  # CI: fail when schema.ts is stale
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const dir = dirname(fileURLToPath(import.meta.url));
const SOURCE = join(dir, "openapi.json");
const TARGET = join(dir, "schema.ts");

const ident = (name) => name.replace(/[^A-Za-z0-9_]/g, "_");
const key = (k) => (/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(k) ? k : JSON.stringify(k));

function ts(s) {
  if (s.$ref) return ident(s.$ref.split("/").pop());
  if (s.const !== undefined) return JSON.stringify(s.const);
  if (s.enum) return s.enum.map((v) => JSON.stringify(v)).join(" | ");
  if (s.anyOf || s.oneOf) return (s.anyOf ?? s.oneOf).map(ts).join(" | ");
  switch (s.type) {
    case "null":
      return "null";
    case "string":
      return "string";
    case "number":
    case "integer":
      return "number";
    case "boolean":
      return "boolean";
    case "array":
      return `Array<${ts(s.items ?? {})}>`;
    case "object": {
      const props = Object.entries(s.properties ?? {});
      if (props.length === 0) {
        const extra = s.additionalProperties;
        return `Record<string, ${extra && extra !== true ? ts(extra) : "unknown"}>`;
      }
      const required = new Set(s.required ?? []);
      const body = props.map(([k, v]) => `  ${key(k)}${required.has(k) ? "" : "?"}: ${ts(v)};`);
      return `{\n${body.join("\n")}\n}`;
    }
    default:
      return "unknown";
  }
}

const schemas = JSON.parse(readFileSync(SOURCE, "utf8")).components?.schemas ?? {};
const out = [
  "// GENERATED by packages/api-contract/generate.mjs from openapi.json - do not edit.",
  "// Regenerate: uv run python scripts/export_openapi.py (apps/api), then node generate.mjs.",
  "",
  ...Object.keys(schemas)
    .sort()
    .map((name) => `export type ${ident(name)} = ${ts(schemas[name])};\n`),
].join("\n");

if (process.argv.includes("--check")) {
  let current = "";
  try {
    current = readFileSync(TARGET, "utf8");
  } catch {}
  if (current !== out) {
    console.error("packages/api-contract/schema.ts is stale - run: node packages/api-contract/generate.mjs");
    process.exit(1);
  }
} else {
  writeFileSync(TARGET, out);
}
