// GENERATED by packages/api-contract/generate.mjs from openapi.json - do not edit.
// Regenerate: uv run python scripts/export_openapi.py (apps/api), then node generate.mjs.

export type AirIndex = {
  level: "GOOD" | "FAIR" | "MODERATE" | "POOR" | "VERY_POOR" | "EXTREMELY_POOR" | null;
  complete: boolean;
  params: Record<string, "GOOD" | "FAIR" | "MODERATE" | "POOR" | "VERY_POOR" | "EXTREMELY_POOR">;
  dominant: Array<string>;
  missing: Record<string, "MISSING" | "STALE" | "UNIT" | "INVALID">;
  valid_until: string | null;
};

export type AirParam = {
  value: number;
  unit: string;
  observed_at: string;
  freshness: "FRESH" | "RECENT" | "STALE";
};

export type AlertOut = {
  external_id: string;
  source: string;
  event_type: string;
  severity_raw: string;
  probability_pct: number | null;
  issuing_office: string;
  description: string;
  comment: string | null;
  areas: Array<Record<string, unknown>>;
  valid_from: string;
  valid_until: string;
  published_at: string;
  fetched_at: string;
  freshness: "FRESH" | "RECENT" | "STALE";
};

export type DashboardAir = {
  station_id: string;
  station_name: string;
  source: "gios";
  attribution: string;
  observed_at: string;
  params: Record<string, AirParam>;
  index: AirIndex;
  distance_km: number;
};

export type DashboardAlerts = {
  scope: "national";
  source: string;
  attribution: string;
  items: Array<AlertOut>;
  source_status: Record<string, SourceStatusOut>;
};

export type DashboardArea = {
  geo_area_id: number;
  slug: string;
  name: string;
  latitude: number;
  longitude: number;
  air: DashboardAir | null;
  weather: DashboardWeather | null;
  forecast: DashboardForecast | null;
  outdoor: DashboardOutdoor;
  pollen: DashboardPollen;
};

export type DashboardForecast = {
  source: "open_meteo";
  attribution: string;
  fetched_at: string;
  freshness: "FRESH" | "RECENT" | "STALE";
  days: Array<DashboardForecastDay>;
};

export type DashboardForecastDay = {
  valid_from: string;
  valid_until: string;
  params: Record<string, WeatherParam>;
};

export type DashboardOutdoor = {
  level: "GOOD" | "MODERATE" | "POOR" | "UNKNOWN";
  reasons: Array<OutdoorReasonOut>;
  missing: Array<OutdoorMissingOut>;
  valid_until: string | null;
};

export type DashboardPollen = {
  source: string;
  attribution: string;
  kind: "model_forecast";
  model: string | null;
  unit: string | null;
  forecast_reference_time: string | null;
  fetched_at: string | null;
  freshness: "FRESH" | "RECENT" | "STALE" | "UNAVAILABLE";
  valid_at: string | null;
  current: PollenValues | null;
  days: Array<DashboardPollenDay>;
  source_status: SourceStatusOut;
};

export type DashboardPollenDay = {
  date: string;
  max: PollenValues;
};

export type DashboardResponse = {
  areas: Array<DashboardArea>;
  alerts: DashboardAlerts;
};

export type DashboardWeather = {
  source: "open_meteo";
  attribution: string;
  observed_at: string;
  freshness: "FRESH" | "RECENT" | "STALE";
  params: Record<string, DashboardWeatherParam>;
};

export type DashboardWeatherParam = {
  value: number;
  unit: string;
  observed_at: string;
  freshness: "FRESH" | "RECENT" | "STALE";
};

export type OutdoorMissingOut = {
  group: string;
  params: Array<string>;
  status: "MISSING" | "STALE" | "INVALID";
  core: boolean;
  blocking: boolean;
};

export type OutdoorReasonOut = {
  code: string;
  param: string;
  value: number;
  threshold: number;
  comparison: "gt" | "gte" | "lt" | "lte";
  unit: string;
  level: "MODERATE" | "POOR";
};

export type PollenValues = {
  alder: number | null;
  birch: number | null;
  grass: number | null;
  mugwort: number | null;
  ragweed: number | null;
};

export type SourceStatusOut = {
  freshness: "FRESH" | "RECENT" | "STALE" | "UNAVAILABLE";
  last_success_at: string | null;
};

export type WeatherParam = {
  value: number;
  unit: string;
};
