// GENERATED by packages/api-contract/generate.mjs from openapi.json - do not edit.
// Regenerate: uv run python scripts/export_openapi.py (apps/api), then node generate.mjs.

export type ActiveTaxon = {
  category: string;
  key: string;
  name_pl: string;
  note: string;
  peak: boolean;
  peak_end: string;
  peak_start: string;
  phase: "start" | "peak" | "end";
  season_end: string;
  season_start: string;
  source_ids: Array<string>;
};

export type AirIndex = {
  complete: boolean;
  dominant: Array<string>;
  level: "GOOD" | "FAIR" | "MODERATE" | "POOR" | "VERY_POOR" | "EXTREMELY_POOR" | null;
  missing: Record<string, "MISSING" | "STALE" | "UNIT" | "INVALID">;
  params: Record<string, "GOOD" | "FAIR" | "MODERATE" | "POOR" | "VERY_POOR" | "EXTREMELY_POOR">;
  valid_until: string | null;
};

export type AirLatestResponse = {
  stations: Array<AirStation>;
};

export type AirParam = {
  freshness: "FRESH" | "RECENT" | "STALE";
  observed_at: string;
  unit: string;
  value: number;
};

export type AirStation = {
  assignment_method?: string | null;
  coverage?: "exact" | "nearby" | "regional" | null;
  coverage_radius_km?: number | null;
  distance_km?: number | null;
  index: AirIndex;
  latitude: number;
  longitude: number;
  params: Record<string, AirParam>;
  source: "gios";
  station_id: string;
  station_name: string;
};

export type AlertOut = {
  areas: Array<Record<string, unknown>>;
  comment: string | null;
  description: string;
  event_type: string;
  external_id: string;
  fetched_at: string;
  freshness: "FRESH" | "RECENT" | "STALE";
  geo_match: "voivodeship" | "unresolved" | null;
  issuing_office: string;
  probability_pct: number | null;
  published_at: string;
  severity_raw: string;
  source: string;
  valid_from: string;
  valid_until: string;
};

export type AlertsLatestResponse = {
  alerts: Array<AlertOut>;
  source_status: Record<string, SourceStatusOut>;
};

export type AreaOut = {
  geo_area_id: number;
  latitude: number;
  longitude: number;
  name: string;
  slug: string;
  teryt_code: string | null;
  weather_polling_active: boolean;
};

export type AreasResponse = {
  areas: Array<AreaOut>;
};

export type DailyBudgetOut = {
  limit: number;
  used: number;
  used_pct: number;
};

export type DashboardAir = {
  assignment_method: string;
  attribution: string;
  coverage: "exact" | "nearby" | "regional";
  coverage_radius_km: number;
  distance_km: number;
  index: AirIndex;
  observed_at: string;
  params: Record<string, AirParam>;
  source: "gios";
  source_status: SourceStatusOut;
  station_id: string;
  station_name: string;
};

export type DashboardAlerts = {
  attribution: string;
  items: Array<AlertOut>;
  scope: "national";
  source: string;
  source_status: Record<string, SourceStatusOut>;
};

export type DashboardArea = {
  air: DashboardAir | null;
  coverage: DashboardCoverage;
  forecast: DashboardForecast | null;
  geo_area_id: number;
  latitude: number;
  local_alerts: Array<AlertOut>;
  longitude: number;
  name: string;
  outdoor: DashboardOutdoor;
  pollen: DashboardPollen;
  slug: string;
  weather: DashboardWeather | null;
  weather_polling_active: boolean;
};

export type DashboardCoverage = {
  air: "exact" | "nearby" | "regional" | "none";
  air_radius_km: number | null;
  grid_description: string;
  pollen: "grid";
  weather: "grid";
};

export type DashboardForecast = {
  attribution: string;
  days: Array<DashboardForecastDay>;
  fetched_at: string;
  freshness: "FRESH" | "RECENT" | "STALE";
  hours: Array<DashboardForecastHour>;
  source: "open_meteo";
};

export type DashboardForecastDay = {
  params: Record<string, WeatherParam>;
  valid_from: string;
  valid_until: string;
};

export type DashboardForecastHour = {
  params: Record<string, WeatherParam>;
  valid_from: string;
  valid_until: string;
};

export type DashboardOutdoor = {
  level: "GOOD" | "MODERATE" | "POOR" | "UNKNOWN";
  missing: Array<OutdoorMissingOut>;
  reasons: Array<OutdoorReasonOut>;
  valid_until: string | null;
};

export type DashboardPollen = {
  attribution: string;
  current: PollenValues | null;
  days: Array<DashboardPollenDay>;
  fetched_at: string | null;
  forecast_reference_time: string | null;
  freshness: "FRESH" | "RECENT" | "STALE" | "UNAVAILABLE";
  kind: "model_forecast";
  model: string | null;
  source: string;
  source_status: SourceStatusOut;
  unit: string | null;
  valid_at: string | null;
};

export type DashboardPollenDay = {
  date: string;
  max: PollenValues;
};

export type DashboardResponse = {
  alerts: DashboardAlerts;
  areas: Array<DashboardArea>;
  source_status: DashboardSourceStatus;
};

export type DashboardSourceStatus = {
  air: SourceStatusOut;
  weather: SourceStatusOut;
};

export type DashboardWeather = {
  attribution: string;
  freshness: "FRESH" | "RECENT" | "STALE";
  observed_at: string;
  params: Record<string, DashboardWeatherParam>;
  source: "open_meteo";
  source_status: SourceStatusOut;
};

export type DashboardWeatherParam = {
  freshness: "FRESH" | "RECENT" | "STALE";
  observed_at: string;
  unit: string;
  value: number;
};

export type DeviceIn = {
  app_version?: string | null;
  installation_id: string;
  observed_area_code?: string | null;
  platform: "android" | "ios";
  push_token?: string | null;
};

export type DeviceOut = {
  active: boolean;
  app_version: string | null;
  device_secret: string | null;
  installation_id: string;
  last_seen_at: string;
  observed_area_code: string | null;
  platform: "android" | "ios";
  push_registered: boolean;
};

export type ForecastArea = {
  days: Array<ForecastDay>;
  fetched_at: string;
  freshness: "FRESH" | "RECENT" | "STALE";
  geo_area_id: number;
  latitude: number;
  longitude: number;
  model: string;
  name: string;
  slug: string;
  source: string;
};

export type ForecastDay = {
  forecast_reference_time: string;
  params: Record<string, WeatherParam>;
  valid_from: string;
  valid_until: string;
};

export type GeoLocateResponse = {
  area: AreaOut | null;
  assignment_method: "point_in_polygon" | "nearest_area" | null;
  distance_km: number | null;
  status: "resolved" | "out_of_range";
};

export type GeoResolveRequest = {
  latitude: number;
  longitude: number;
};

export type GeoResolveResponse = {
  area: ResolvedGeoArea | null;
};

export type HTTPValidationError = {
  detail?: Array<ValidationError>;
};

export type HydroLatestResponse = {
  attribution: string;
  source_status: SourceStatusOut;
  stations: Array<HydroStation>;
};

export type HydroStation = {
  alarm_level_cm: number | null;
  freshness: "FRESH" | "RECENT" | "STALE";
  latitude: number;
  longitude: number;
  observed_at: string;
  source: "imgw_hydro";
  station_id: string;
  station_name: string;
  status: "NORMAL" | "WARNING" | "ALARM" | "UNKNOWN";
  unit: string;
  warning_level_cm: number | null;
  water_level_cm: number;
};

export type NearestPlaceResponse = {
  attribution: string;
  distance_km: number | null;
  place: PlaceOut | null;
  status: "found" | "out_of_range";
};

export type NeighborhoodOut = {
  area_name: string;
  enabled: boolean;
  geo_area_id: number;
  sections: Array<NoiseSectionOut>;
};

export type NoiseItemOut = {
  category: "Droga" | "Lotnisko" | "Przemysł" | "Kolej";
  distance_km: number;
  gmina: string | null;
  locality: string | null;
  measurements: Array<NoiseMeasurementOut>;
  period_from: string;
  period_to: string;
  point_code: string;
  purpose: string | null;
  voivodeship: string;
};

export type NoiseMeasurementOut = {
  exceedance_db: number | null;
  period_of_day: string;
  value_db: number;
};

export type NoiseSectionOut = {
  attribution: string;
  availability: "available" | "no_coverage" | "no_records" | "unavailable" | "pending_verification";
  data_kind: "historical_measurement";
  fetched_at: string | null;
  id: "noise";
  items: Array<NoiseItemOut>;
  license_url: string;
  limitations: Array<string>;
  message: string | null;
  retrieval_status: "ok" | "degraded" | "none";
  search_radius_km: number;
  source_period: SourcePeriod | null;
  source_url: string;
  title: string;
};

export type NotCovered = {
  key: string;
  name_pl: string;
  reason: string;
};

export type OutdoorMissingOut = {
  blocking: boolean;
  core: boolean;
  group: string;
  params: Array<string>;
  status: "MISSING" | "STALE" | "INVALID";
};

export type OutdoorReasonOut = {
  code: string;
  comparison: "gt" | "gte" | "lt" | "lte";
  level: "MODERATE" | "POOR";
  param: string;
  threshold: number;
  unit: string;
  value: number;
};

export type PlaceAreaResponse = {
  area: AreaOut | null;
  attribution: string;
  place: PlaceOut;
  polling: "active" | "inactive" | "capacity_reached" | "budget_exhausted";
};

export type PlaceOut = {
  admin1_code: string | null;
  admin2_code: string | null;
  kind: string;
  label: string;
  latitude: number;
  longitude: number;
  name: string;
  place_id: number;
  population: number | null;
};

export type PlacesResponse = {
  attribution: string;
  places: Array<PlaceOut>;
};

export type PollenArea = {
  current: PollenValues | null;
  days: Array<PollenDay>;
  fetched_at: string;
  forecast_reference_time: string;
  freshness: "FRESH" | "RECENT" | "STALE";
  geo_area_id: number;
  kind: "model_forecast";
  latitude: number;
  longitude: number;
  model: string;
  name: string;
  slug: string;
  unit: string;
  valid_at: string | null;
};

export type PollenCalendarOut = {
  active: Array<ActiveTaxon>;
  active_message: string | null;
  attribution: string;
  coverage_complete: false;
  coverage_warning: string;
  date: string;
  disclaimer: string;
  kind: "seasonal_calendar";
  not_covered: Array<NotCovered>;
  region: "PL";
  reviewed_at: string;
  sources: Record<string, Source>;
  upcoming: Array<UpcomingTaxon>;
  upcoming_within_days: number;
};

export type PollenDay = {
  date: string;
  max: PollenValues;
};

export type PollenLatestResponse = {
  areas: Array<PollenArea>;
  attribution: string;
  source: string;
  source_status: SourceStatusOut;
};

export type PollenValues = {
  alder: number | null;
  birch: number | null;
  grass: number | null;
  mugwort: number | null;
  ragweed: number | null;
};

export type ResolvedGeoArea = {
  geo_area_id: number;
  name: string;
  slug: string;
  teryt_code: string;
};

export type Source = {
  checked_at: string;
  citation: string;
  license: string;
  url: string;
};

export type SourceHealthOut = {
  daily_budget: DailyBudgetOut | null;
  freshness: "FRESH" | "RECENT" | "STALE" | "UNAVAILABLE";
  last_attempt_at: string | null;
  last_error: string | null;
  last_success_at: string | null;
  monitored: boolean;
  source_id: string;
};

export type SourcePeriod = {
  from: string;
  precision: "date" | "year" | "range" | "unknown";
  to: string;
};

export type SourceStatusOut = {
  freshness: "FRESH" | "RECENT" | "STALE" | "UNAVAILABLE";
  last_success_at: string | null;
};

export type SourcesHealthResponse = {
  generated_at: string;
  sources: Array<SourceHealthOut>;
};

export type UpcomingTaxon = {
  category: string;
  days_until: number;
  key: string;
  name_pl: string;
  note: string;
  season_end: string;
  source_ids: Array<string>;
  starts_on: string;
};

export type ValidationError = {
  ctx?: Record<string, unknown>;
  input?: unknown;
  loc: Array<string | number>;
  msg: string;
  type: string;
};

export type WeatherArea = {
  freshness: "FRESH" | "RECENT" | "STALE";
  geo_area_id: number;
  latitude: number;
  longitude: number;
  name: string;
  observed_at: string;
  params: Record<string, WeatherLatestParam>;
  slug: string;
  source: string;
};

export type WeatherForecastResponse = {
  areas: Array<ForecastArea>;
};

export type WeatherLatestParam = {
  freshness: "FRESH" | "RECENT" | "STALE";
  observed_at: string;
  unit: string;
  value: number;
};

export type WeatherLatestResponse = {
  areas: Array<WeatherArea>;
};

export type WeatherParam = {
  unit: string;
  value: number;
};
